[package]
name = "web_bmi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
lazy_static = "1.4.0"
serde = {version = "1.0.173", features = ["derive"]}
tera = "1.19.0"
